
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web_BanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Combo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Combo()
    {

        this.InvoiceDetails = new HashSet<InvoiceDetail>();

    }


    public int ID { get; set; }

    public string Combo_Name { get; set; }

    public string Product_List { get; set; }

    public Nullable<System.DateTime> startDate { get; set; }

    public Nullable<System.DateTime> endDate { get; set; }

    public string totalMoney { get; set; }

    public string discount { get; set; }

    public string discountMoney { get; set; }

    public string Image_Combo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }

}

}
