//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public int ID { get; set; }
        public string Combo_Name { get; set; }
        public string Product_List { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> totalMoney { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> discountMoney { get; set; }
    }
}
