
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web_BanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Invoices = new HashSet<Invoice>();

        this.Invoices1 = new HashSet<Invoice>();

    }


    public int ID { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string phoneNumber { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string gender { get; set; }

    public Nullable<System.DateTime> birthDate { get; set; }

    public string address { get; set; }

    public Nullable<System.DateTime> joinDate { get; set; }

    public Nullable<int> isNew { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice> Invoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice> Invoices1 { get; set; }

}

}
