//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Catalog_ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Price { get; set; }
        public string Image_Name { get; set; }
        public string Detail { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
