//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int Product_ID { get; set; }
        public int Amount { get; set; }
        public System.DateTime importDate { get; set; }
        public System.DateTime exportDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
